-   id: ktfmt-pre-commit-hook
    name: ktfmt Kotlin automatic code formatter
    description: This hook runs ktfmt (https://github.com/facebookincubator/ktfmt) on Kotlin source files.
    entry: ktfmt-pre-commit-hook
    language: python
    types: [kotlin]
    minimum_pre_commit_version: '2.15'